### ISSUE TITLE
Clicking a tile doesn't work after resize

### ISSUE THREAD

**Issue by watabou** [Arcnor/pixel-dungeon-gdx#7]
After resizing a window on desktop and changing orientation on iOS the map stops responding on tapping, but it still can be dragged without a problem. After tapping any ui element (toolbar buttons, hero's avatar etc) everything gets back to normal.

**Comment by Arcnor** [comment]
Yeah, forgot to mention this. This wasn't happening on the original code because you were relying on the Activity being completely destroyed, but that doesn't happen with LibGDX (the Activity might be getting destroyed, but our game class is not).

The listener of the CellSelector gets set to `null` (because we're recreating all the objects when calling `switchScene()` on the `resize` handler). We might want to "reset" the game in a different way, without recreating those objects.
